"""user activity

Revision ID: 1623c1e960d0
Revises: a6ade494c36c
Create Date: 2025-08-14 20:57:47.444954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1623c1e960d0'
down_revision = 'a6ade494c36c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clothing_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('reported_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')

    with op.batch_alter_table('clothing_item', schema=None) as batch_op:
        batch_op.drop_column('reported_count')
        batch_op.drop_column('status')

    op.drop_table('user_activity')
    # ### end Alembic commands ###
