"""Add items_snapshot to Outfit model

Revision ID: 1a589b184768
Revises: efce3b9a54f6
Create Date: 2025-09-11 21:21:02.874522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a589b184768'
down_revision = 'efce3b9a54f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfit', schema=None) as batch_op:
        batch_op.drop_column('items_snapshot')
    # ### end Alembic commands ###
