"""Add is_verified to User model

Revision ID: 211b3916030e
Revises: b48b0342876a
Create Date: 2025-08-10 11:31:13.896677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211b3916030e'
down_revision = 'b48b0342876a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')
    # ### end Alembic commands ###