"""Add brand table and relationship

Revision ID: 2498ca3a7349
Revises: 76cbea2245f5
Create Date: 2025-09-07 15:59:28.300642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2498ca3a7349'
down_revision = '76cbea2245f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    # CORRECTED: Added server_default=sa.false()
    sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.false()),
    # CORRECTED: Added server_default and made nullable=False for data integrity
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.create_index('ix_brand_name', ['name'], unique=False)

    with op.batch_alter_table('clothing_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        # Note: A data migration will be needed later to populate this from the old 'brand' column.
        batch_op.create_foreign_key('fk_clothing_item_brand_id', 'brand', ['brand_id'], ['id'])
        batch_op.drop_column('brand')

    # REMOVED: Redundant operations for 'negative_prompt' and 'packing_list_feedback'
    # as they were handled in previous migrations.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothing_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_clothing_item_brand_id', type_='foreignkey')
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_index('ix_brand_name')

    op.drop_table('brand')
    # ### end Alembic commands ###
