"""Negative Promt added

Revision ID: 3433c4d54794
Revises: 0489ee7c6c3c
Create Date: 2025-09-02 16:34:40.391664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3433c4d54794'
down_revision = '0489ee7c6c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negative_prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.String(length=512), nullable=False),
    # --- THIS LINE HAS BEEN MODIFIED ---
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # The 'batch_alter_table' block for 'packing_list_feedback' has been removed.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('negative_prompt')
    # The 'batch_alter_table' block for 'packing_list_feedback' has been removed.
    # ### end Alembic commands ###
