"""Add profile fields and settings to User model

Revision ID: 39744d8cfe81
Revises: 
Create Date: 2025-07-27 19:35:02.231028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39744d8cfe81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('laundry_preferences', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clothing_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('fabric', sa.String(length=50), nullable=True),
    sa.Column('mood_tags', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('is_clean', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('custom_tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('wear_count', sa.Integer(), nullable=True),
    sa.Column('wear_count_since_wash', sa.Integer(), nullable=True),
    sa.Column('last_worn', sa.DateTime(), nullable=True),
    sa.Column('last_washed', sa.DateTime(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('purchase_cost', sa.Float(), nullable=True),
    sa.Column('laundry_status', sa.String(length=20), nullable=True),
    sa.Column('needs_washing', sa.Boolean(), nullable=True),
    sa.Column('wash_urgency', sa.String(length=20), nullable=True),
    sa.Column('care_instructions', sa.Text(), nullable=True),
    sa.Column('wash_temperature', sa.String(length=20), nullable=True),
    sa.Column('dry_clean_only', sa.Boolean(), nullable=True),
    sa.Column('needs_repair', sa.Boolean(), nullable=True),
    sa.Column('repair_notes', sa.Text(), nullable=True),
    sa.Column('retirement_candidate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outfit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weather', sa.String(length=100), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('was_actually_worn', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outfit_items',
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('clothing_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clothing_item_id'], ['clothing_item.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfit.id'], ),
    sa.PrimaryKeyConstraint('outfit_id', 'clothing_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outfit_items')
    op.drop_table('outfit')
    op.drop_table('clothing_item')
    op.drop_table('user')
    # ### end Alembic commands ###
