"""add stripe fields to user

Revision ID: 3b476139cb41
Revises: cc655e9b9520
Create Date: 2025-08-19 20:42:58.273012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b476139cb41'
down_revision = 'cc655e9b9520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True))
        # Provide an explicit name for the constraint
        batch_op.create_unique_constraint('uq_user_stripe_customer_id', ['stripe_customer_id'])
        # Provide an explicit name for the constraint
        batch_op.create_unique_constraint('uq_user_stripe_subscription_id', ['stripe_subscription_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Use the same explicit names to drop the constraints
        batch_op.drop_constraint('uq_user_stripe_subscription_id', type_='unique')
        batch_op.drop_constraint('uq_user_stripe_customer_id', type_='unique')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    op.drop_table('app_settings')
    # ### end Alembic commands ###
