"""subsription id

Revision ID: 4049418e1ca5
Revises: 6f2e4f89d6dc
Create Date: 2025-08-27 15:45:14.874478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4049418e1ca5'
down_revision = '6f2e4f89d6dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('customer_portal_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_portal_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('subscription_id')

    # ### end Alembic commands ###
