"""Add fit and pattern to CLothingItem

Revision ID: 4178ef0302d1
Revises: 4049418e1ca5
Create Date: 2025-08-29 09:34:18.191909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4178ef0302d1'
down_revision = '4049418e1ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothing_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pattern', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothing_item', schema=None) as batch_op:
        batch_op.drop_column('pattern')
        batch_op.drop_column('fit')

    # ### end Alembic commands ###
