"""customer portal

Revision ID: 6f2e4f89d6dc
Revises: c5ed9d82f2fb
Create Date: 2025-08-26 22:38:10.884678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2e4f89d6dc'
down_revision = 'c5ed9d82f2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_portal_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('customer_portal_url')

    # ### end Alembic commands ###
