"""onboarding & app tour

Revision ID: 76cbea2245f5
Revises: 3433c4d54794
Create Date: 2025-09-05 23:02:10.082303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76cbea2245f5'
down_revision = '3433c4d54794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The changes for 'negative_prompt' and 'packing_list_feedback' were removed
    # from this migration as they were already applied in a previous one.
    # This migration now correctly focuses only on the changes to the 'user' table.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_completed_onboarding', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('has_seen_app_tour', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Matching the upgrade function, the downgrade now only reverses
    # the changes made to the 'user' table.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_seen_app_tour')
        batch_op.drop_column('has_completed_onboarding')

    # ### end Alembic commands ###

