"""moderation data

Revision ID: a6ade494c36c
Revises: ae8a57f3ee1a
Create Date: 2025-08-13 20:10:37.268494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ade494c36c'
down_revision = 'ae8a57f3ee1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothing_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='available'))
        batch_op.add_column(sa.Column('reported_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothing_item', schema=None) as batch_op:
        batch_op.drop_column('reported_count')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
