"""Add reasoning column to packing_list table

Revision ID: ac2d5976fa8c
Revises: 4178ef0302d1
Create Date: 2025-09-01 20:56:20.105670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2d5976fa8c'
down_revision = '4178ef0302d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packing_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasoning', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packing_list', schema=None) as batch_op:
        batch_op.drop_column('reasoning')

    # ### end Alembic commands ###
