"""Add outfit generation tracking fields to User model

Revision ID: efce3b9a54f6
Revises: 2498ca3a7349
Create Date: 2025-09-08 15:07:44.293187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efce3b9a54f6'
down_revision = '2498ca3a7349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # REMOVED: Redundant operations for 'brand', 'negative_prompt', 
    # and 'packing_list_feedback' as they were handled in previous migrations.

    with op.batch_alter_table('user', schema=None) as batch_op:
        # CORRECTED: Added server_default='0' for existing users.
        batch_op.add_column(sa.Column('outfit_generations_today', sa.Integer(), nullable=False, server_default='0'))
        # CORRECTED: Added server_default to use the current date for existing users.
        batch_op.add_column(sa.Column('last_generation_date', sa.Date(), nullable=False, server_default=sa.func.current_date()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_generation_date')
        batch_op.drop_column('outfit_generations_today')

    # REMOVED: Redundant downgrade operations for other tables.

    # ### end Alembic commands ###
